### ISSUE TITLE
Minion movement blocked by "off turn movement"

### ISSUE THREAD

**Issue by sherman-jordan** [illandril/FoundryVTT-turn-marker#7]
**Is your feature request related to a problem? Please describe.**
I find off-turn movement being blocked will also block the movement of tokens (e.g. animal companions) created using Pf2e Companion Compendia. These Actors are moved on their controlling PC's turn and don't get added to initiative order, effectively blocking players from moving them without GM assistance during combat.

**Describe the solution you'd like**
When token movement is unblocked for an actor during its turn, movement is also unblocked for other tokens owned by the same player. Perhaps this can be somehow restricted to actors with a specific characteristic in their character sheet (e.g. "Minion") to account for Eidolons / Familiars / Animal Companions (which move on their master's turn.) 

**Describe alternatives you've considered**
At the moment I am having my druid ping the map where she would like her animal companion moved to and using the "m" key to override. It's not as nice as her being granted movement of the token directly but it works without having to disable the feature.

**What system(s) do you want this feature to work with?**
Pathfinder 2e

**What other modules do you use that you want to ensure work well with this feature?**
PF2e Companion Compendia

**Additional context**

**Comment by illandril** [comment]
"Familiars" type actors in pf2e are now allowed to move on the turn of their "Master" (as are actors for any other system that get linked to another token's turn via `token.actor.combatant` properties).

There are also now two extra settings...
- Allow Same Initiative Movement
  - Allows tokens that share the same initiative value to move on each other's turn
- Allow Non-Combatant Movement
  - Allows tokens that aren't in the initiative tracker to move on any turn

This isn't exactly what you asked for, so if this doesn't fit your specific use case let me know and I can see if I can add more configuration options to handle more of the many "this token should be allowed to move on this other token's turn" cases.

For my games, I have two people sharing one computer, and they're the two most likely to make a mistake (and the reason I added the "Block Off Turn Movement" feature), so I need to be careful not to accidentally allow them to move a character on the wrong turn.
